### PR TITLE
Add convenience function to broadcast to multiple sessions

### PR DESCRIPTION
**Pull request by robbiet480**

### CODE REVIEW

**Comment by olahol** [comment]
Wouldn't this be better implemented as a loop over the session slice and `session.Write`? It looks like it's
`O(n^2)` in complexity right now.

**Comment by robbiet480** [comment]
@olahol duh! I just had this little bit of code hanging out unused in my private base and didn't think to check it for complexity before submitting. Will get it fixed now.

**Comment by robbiet480** [comment]
@olahol Fixed!

**Comment by olahol** [comment]
Thank you @robbiet480, nice work :+1:

**Pull request merged**
